name: Trigger Frontend Build

on:
  push:
    branches:
      - master
jobs:
  ping-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Frontend Repo
        run: |
          curl -H "Authorization: token ${{ secrets.BUILD_TRIGGER_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -X POST \
               -d '{"event_type": "dependency_updated"}' \
               https://api.github.com/repos/AAccount/assemblechinese_jsefrontend/dispatches
